version: "3"
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library
    networks:
      - library-net

  auth-service:
    build: ./auth
    ports:
      - "8081:8081"
    networks:
      - library-net

  books-service:
    build: ./book
    ports:
      - "8082:8082"
    networks:
      - library-net

  frontend-service:
    build: ./frontend
    ports:
      - "8080:8080"
    networks:
      - library-net

networks:
  library-net:
    driver: bridge
